platform :osx, '10.7'
# pod 'DPHue', :local => '~/cp/DPHue'
pod 'DPHue', :git => 'https://github.com/jtdreisb/DPHue.git'
pod 'DPHue', '~> 0.0.1'
pod 'INAppStoreWindow', :git => 'https://github.com/jtdreisb/INAppStoreWindow.git'
pod 'INAppStoreWindow', '~> 1.2'
